FROM oven/bun:alpine

WORKDIR /usr/src/app

COPY ./package.json ./package.json

RUN bun install

COPY ./packages ./packages
COPY ./apps/api ./apps/api

RUN bun install

RUN bunx prisma@6.19.3 generate --schema=./packages/store/prisma/schema.prisma

EXPOSE 8080

CMD [ "bun", "run", "apps/api/index.ts" ]